# This instructs Ansible to install the required collections from Ansible Galaxy
collections:
  - name: containers.podman
  - name: community.general
  - name: abalage.elasticstack_podman
#    source: git+https://github.com/abalage/ansible_collection_elasticstack_podman.git
